---
title: "Getting and Cleaning Data Course Project"
output:
  pdf_document:
    toc: yes
    toc_depth: 6
    number_sections: yes
    latex_engine: xelatex
    df_print: kable
    highlight: tango
  html_notebook: default
  html_document:
    toc: yes
    toc_depth: '6'
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '6'
---

# Getting and Cleaning Data Course Project

## Project Description

One of the most exciting areas in all of data science right now is wearable computing - see for example [this article](http://www.insideactivitytracking.com/data-science-activity-tracking-and-the-battle-for-the-worlds-top-sports-brand/) . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. 

## Informations on the original data 

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.  

## Guide to create the tidy data file

1. Merges the training and the test sets to create one data set.
    
2. Extracts only the measurements on the mean and standard deviation for each measurement.
    
3. Uses descriptive activity names to name the activities in the data set
    
4. Appropriately labels the data set with descriptive variable names.
    
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

see `run_analysis.R` file for details.

## Code Implementation

### Getting the raw data 

```{r}
# check if the data folder exists
```

