---
title: "Week 3 Quiz"
output:
  pdf_document:
    toc: yes
    toc_depth: 6
    number_sections: yes
    latex_engine: xelatex
    df_print: kable
    highlight: tango
  html_notebook: default
  html_document:
    toc: yes
    toc_depth: '6'
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '6'
---

# Week 3 Quiz

```{r}
df1 <- read.csv("data/getdata_data_ss06hid.csv")
```

```{r}
head(df1)
```

```{r}
library(plyr)
library(dplyr)
```

```{r}
df1 %>%
  filter(ACR == 3 & AGS ==6) 
```

```
X[(X$var1 <= 3 & X$var3 > 11),] # get all rows that meets the condition
```

```{r}
agLogical <- df1$ACR == 3 & df1$AGS == 6
```

```{r}
which(agLogical)
```

```{r}
if(!file.exists("data")) {
  dir.create("data")
}

fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fjeff.jpg"

download.file(fileUrl,destfile = "data/img.jpg", method = "curl")
```

```{r}
library(jpeg)
```

```{r}
img <- readJPEG("data/img.jpg",native = TRUE)
```

```{r}
head(img)
```

```{r}
quantile(img,0.3)
```

```{r}
quantile(img,0.8)
```

```{r}
# Unroll the matrix into a single vector
img_vector <- as.vector(img)
```

```{r}
quantile(img_vector, 0.30)
```

```{r}
quantile(img_vector, 0.80)
```

```{r}
gdp <- read.csv("data/gdp.csv")
```

```{r}
edu <- read.csv("data/edu.csv")
```

```{r}
head(gdp)
```


```{r}
head(edu)
```

```{r}
mergedData = merge(gdp,edu,by.x="X",by.y="CountryCode",all=TRUE)
head(mergedData)
```

```{r}
names(gdp)[1] <- "CountryCode"
```

```{r}
names(gdp)
```

```{r}
names(edu)
```

```{r}
merged <- merge(edu, gdp, by = "CountryCode")
```

```{r}
head(merged)
```

```{r}
str(mergedData)
```

```{r}
str(merged)
```

