---
title: "R Notebook"
output: html_notebook
---

```{r}
x <-4L 
class(x)
```

```{r}
x<-c(4,"a",TRUE)
class(x)
```

```{r}
x <- c(1,3,5)
x
```

```{r}
y <-c(3,2,10)
y
```
```{r}
rbind(x,y)
```
```{r}
class(rbind(x,y))
```


```{r}
x8 <- list(2,"a","b",TRUE)
x8
```
```{r}
x8[[2]]
```
```{r}
class(x8[[2]])
```

```{r}
x <- 1:4 
y <- 2:3 

```

```{r}
x
```
```{r}
y
```
```{r}
x+y
```

```{r}
class(x +y)
```
```{r}
class(x +y)[1]
```

```{r}
x <- c(3, 5, 1, 10, 12, 6)
x
```

```{r}
x[x > 6] <- 0
x
```
```{r}
x <- c(3, 5, 1, 10, 12, 6)

```

```{r}
data <- read.csv("hw1_data2.csv")
```

```{r}
str(data)
```

```{r}
data[1:2,]
```

```{r}
data[-2,]
```

```{r}
last_two_rows <- tail(data, 2)
last_two_rows
```

```{r}
data[47,]$Ozone
```

```{r}
head(data)
```

```{r}
num.na <- sum(is.na(data$Ozone))
num.na
```
```{r}
oz <- data$Ozone[!is.na(data$Ozone)]
oz
```

```{r}
mean(oz)
```

```{r}
mean(data$Ozone, na.rm = TRUE)
```

```{r}
mean(data[data$Ozone > 31 & data$Temp > 90, ]$`Solar.R`, na.rm = TRUE)
```

```{r}
mean(data[data$Month == 6, ]$Temp, na.rm = TRUE)
```

```{r}
max(data[data$Month == 5, ]$Ozone, na.rm = TRUE)
```

## Trial 2

```{r}
x <- 4L
class(x)
```

```{r}
x <- c(4,TRUE)
class(x)
```
```{r}
x<- list(2,"a","b",TRUE)
x[[1]]
class(x[[1]])
```

```{r}
x <- c(17,14,4,5,13,12,10)
x[x>10]==4
```

```{r}
dt <- read.csv("hw1_data2.csv")
dt
```

